# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d93830d1ad79c15b44e7fecaed8776a57f4ed0ef8e9f435300cd553af6ab18ae1700c78b25c6f5347da8143e6d75ef83187b7e99761fccbe271f9d323a045877

test:
  secret_key_base: d4f8c3f9f0674a99e3bd596a58862035fe7ecf3b60e6e6a147ad2e804686f1dd00131a4b8d6a1993b1732f7cbe7fe28862143b5b19ba7a7f66e3274a1f9b5b70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
